from tkinter import *



root = Tk()
for row_index in range(4):
    Grid.rowconfigure(root, row_index, weight=1)
    for col_index in range(4):
        Grid.columnconfigure(root, col_index, weight=1)
def s1():
    
       btn1.configure(bg="red")
       btn1.configure(state="disabled")
       btn2.configure(state="disabled")
       btn3.configure(state="disabled")
       btn4.configure(state="disabled")
       btn5.configure(state="disabled")
       btn9.configure(state="disabled")
       btn13.configure(state="disabled")
       btn6.configure(state="disabled")
       btn11.configure(state="disabled")
       btn16.configure(state="disabled")
def s2():
    
       btn2.configure(bg="red")
       btn1.configure(state="disabled")
       btn2.configure(state="disabled")
       btn3.configure(state="disabled")
       btn4.configure(state="disabled")
       btn6.configure(state="disabled")
       btn10.configure(state="disabled")
       btn14.configure(state="disabled")
       btn5.configure(state="disabled")
       btn7.configure(state="disabled")
       btn12.configure(state="disabled")
def s3():
    
       btn3.configure(bg="red")
       btn1.configure(state="disabled")
       btn2.configure(state="disabled")
       btn3.configure(state="disabled")
       btn4.configure(state="disabled")
       btn7.configure(state="disabled")
       btn11.configure(state="disabled")
       btn15.configure(state="disabled")
       btn6.configure(state="disabled")
       btn9.configure(state="disabled")
       btn8.configure(state="disabled")
def s4():
    
       btn4.configure(bg="red")
       btn1.configure(state="disabled")
       btn2.configure(state="disabled")
       btn3.configure(state="disabled")
       btn4.configure(state="disabled")
       btn8.configure(state="disabled")
       btn12.configure(state="disabled")
       btn16.configure(state="disabled")
       btn7.configure(state="disabled")
       btn10.configure(state="disabled")
       btn13.configure(state="disabled")
def s5():
    
       btn5.configure(bg="red")
       btn1.configure(state="disabled")
       btn2.configure(state="disabled")
       btn15.configure(state="disabled")
       btn5.configure(state="disabled")
       btn9.configure(state="disabled")
       btn13.configure(state="disabled")
       btn6.configure(state="disabled")
       btn7.configure(state="disabled")
       btn8.configure(state="disabled")
       btn10.configure(state="disabled")
def s6():
    
       btn6.configure(bg="red")
       btn1.configure(state="disabled")
       btn2.configure(state="disabled")
       btn3.configure(state="disabled")
       btn5.configure(state="disabled")
       btn7.configure(state="disabled")
       btn8.configure(state="disabled")
       btn9.configure(state="disabled")
       btn3.configure(state="disabled")
       btn11.configure(state="disabled")
       btn16.configure(state="disabled")
def s7():
    
       btn7.configure(bg="red")
       btn5.configure(state="disabled")
       btn6.configure(state="disabled")
       btn7.configure(state="disabled")
       btn8.configure(state="disabled")
       btn2.configure(state="disabled")
       btn10.configure(state="disabled")
       btn14.configure(state="disabled")
       btn3.configure(state="disabled")
       btn9.configure(state="disabled")
       btn1.configure(state="disabled")
       btn16.configure(state="disabled")
       btn11.configure(state="disabled")
def s8():
    
       btn8.configure(bg="red")
       btn4.configure(state="disabled")
       btn12.configure(state="disabled")
       btn16.configure(state="disabled")
       btn5.configure(state="disabled")
       btn6.configure(state="disabled")
       btn7.configure(state="disabled")
       btn8.configure(state="disabled")
       btn11.configure(state="disabled")
       btn14.configure(state="disabled")
       btn3.configure(state="disabled")
def s9():
    
       btn9.configure(bg="red")
       btn1.configure(state="disabled")
       btn5.configure(state="disabled")
       btn9.configure(state="disabled")
       btn13.configure(state="disabled")
       btn10.configure(state="disabled")
       btn11.configure(state="disabled")
       btn12.configure(state="disabled")
       btn6.configure(state="disabled")
       btn3.configure(state="disabled")
       btn14.configure(state="disabled")
def s10():
    
       btn10.configure(bg="red")
       btn9.configure(state="disabled")
       btn10.configure(state="disabled")
       btn11.configure(state="disabled")
       btn12.configure(state="disabled")
       btn6.configure(state="disabled")
       btn2.configure(state="disabled")
       btn14.configure(state="disabled")
       btn7.configure(state="disabled")
       btn4.configure(state="disabled")
       btn13.configure(state="disabled")
       btn5.configure(state="disabled")
       btn15.configure(state="disabled")
def s11():
    
       btn11.configure(bg="red")
       btn9.configure(state="disabled")
       btn10.configure(state="disabled")
       btn11.configure(state="disabled")
       btn12.configure(state="disabled")
       btn3.configure(state="disabled")
       btn7.configure(state="disabled")
       btn15.configure(state="disabled")
       btn1.configure(state="disabled")
       btn6.configure(state="disabled")
       btn16.configure(state="disabled")
       btn8.configure(state="disabled")
       btn14.configure(state="disabled")
def s12():
    
       btn12.configure(bg="red")
       btn12.configure(state="disabled")
       btn8.configure(state="disabled")
       btn4.configure(state="disabled")
       btn16.configure(state="disabled")
       btn10.configure(state="disabled")
       btn9.configure(state="disabled")
       btn11.configure(state="disabled")
       btn2.configure(state="disabled")
       btn7.configure(state="disabled")
       btn15.configure(state="disabled")
def s13():
    
       btn13.configure(bg="red")
       btn1.configure(state="disabled")
       btn5.configure(state="disabled")
       btn9.configure(state="disabled")
       btn13.configure(state="disabled")
       btn14.configure(state="disabled")
       btn15.configure(state="disabled")
       btn16.configure(state="disabled")
       btn10.configure(state="disabled")
       btn7.configure(state="disabled")
       btn4.configure(state="disabled")
def s14():
    
       btn14.configure(bg="red")
       btn2.configure(state="disabled")
       btn6.configure(state="disabled")
       btn10.configure(state="disabled")
       btn13.configure(state="disabled")
       btn14.configure(state="disabled")
       btn15.configure(state="disabled")
       btn16.configure(state="disabled")
       btn11.configure(state="disabled")
       btn8.configure(state="disabled")
       btn9.configure(state="disabled")
def s15():
    
       btn15.configure(bg="red")
       btn13.configure(state="disabled")
       btn14.configure(state="disabled")
       btn15.configure(state="disabled")
       btn16.configure(state="disabled")
       btn3.configure(state="disabled")
       btn7.configure(state="disabled")
       btn11.configure(state="disabled")
       btn12.configure(state="disabled")
       btn10.configure(state="disabled")
       btn5.configure(state="disabled")
def s16():
    
       btn16.configure(bg="red")
       btn13.configure(state="disabled")
       btn14.configure(state="disabled")
       btn15.configure(state="disabled")
       btn16.configure(state="disabled")
       btn12.configure(state="disabled")
       btn8.configure(state="disabled")
       btn4.configure(state="disabled")
       btn11.configure(state="disabled")
       btn6.configure(state="disabled")
       btn1.configure(state="disabled")

btn1 = Button(root,command=s1)
btn1.grid(column=0, row=0, sticky=N+S+E+W)
btn2 = Button(root,command=s2)
btn2.grid(column=1, row=0, sticky=N+S+E+W)
btn3 = Button(root,command=s3)
btn3.grid(column=2, row=0, sticky=N+S+E+W)
btn4 = Button(root,command=s4)
btn4.grid(column=3, row=0, sticky=N+S+E+W)
btn5 = Button(root,command=s5)
btn5.grid(column=0, row=1, sticky=N+S+E+W)
btn6 = Button(root,command=s6)
btn6.grid(column=1, row=1, sticky=N+S+E+W)
btn7 = Button(root,command=s7)
btn7.grid(column=2, row=1, sticky=N+S+E+W)
btn8 = Button(root,command=s8)
btn8.grid(column=3, row=1, sticky=N+S+E+W)
btn9 = Button(root,command=s9)
btn9.grid(column=0, row=2, sticky=N+S+E+W)
btn10 = Button(root,command=s10)
btn10.grid(column=1, row=2, sticky=N+S+E+W)
btn11 = Button(root,command=s11)
btn11.grid(column=2, row=2, sticky=N+S+E+W)
btn12 = Button(root,command=s12)
btn12.grid(column=3, row=2, sticky=N+S+E+W)
btn13 = Button(root,command=s13)
btn13.grid(column=0, row=3, sticky=N+S+E+W)
btn14 = Button(root,command=s14)
btn14.grid(column=1, row=3, sticky=N+S+E+W)
btn15 = Button(root,command=s15)
btn15.grid(column=2, row=3, sticky=N+S+E+W)
btn16 = Button(root,command=s16)
btn16.grid(column=3, row=3, sticky=N+S+E+W)
mainloop()
